// Adds habitat fields to species.json: host trees, soil and special habitats.
// Written from field-guide knowledge, not checked against a single source.
// trees: mycorrhiza partners; soil: calc | acid | any; extra: special habitats.
import { readFile, writeFile } from 'node:fs/promises';

const H = {
  'Boletus edulis': ['spruce pine beech oak birch', 'acid'],
  'Boletus reticulatus': ['oak beech chestnut lime', 'any'],
  'Boletus pinophilus': ['pine spruce', 'acid'],
  'Boletus aereus': ['oak chestnut beech', 'acid'],
  'Butyriboletus regius': ['beech oak', 'calc'],
  'Butyriboletus appendiculatus': ['oak beech', 'calc'],
  'Butyriboletus fechtneri': ['oak beech lime', 'calc'],
  'Butyriboletus pseudoregius': ['beech oak', 'calc'],
  'Butyriboletus subappendiculatus': ['spruce fir', 'acid'],
  'Caloboletus calopus': ['spruce fir beech', 'acid'],
  'Caloboletus radicans': ['oak beech lime', 'calc'],
  'Caloboletus kluzakii': ['oak', 'calc'],
  'Rubroboletus satanas': ['beech oak', 'calc'],
  'Rubroboletus legaliae': ['oak beech', 'calc'],
  'Rubroboletus rhodoxanthus': ['oak beech', 'calc'],
  'Rubroboletus rubrosanguineus': ['spruce fir', 'calc'],
  'Rubroboletus lupinus': ['oak', 'calc'],
  'Rubroboletus pulcherrimus': ['fir douglas', 'any'],
  'Rubroboletus dupainii': ['oak', 'any'],
  'Rubroboletus pulchrotinctus': ['oak beech', 'calc'],
  'Rubroboletus demonensis': ['holmoak oak', 'any'],
  'Imperator rhodopurpureus': ['oak beech', 'acid'],
  'Imperator torosus': ['beech oak', 'calc'],
  'Imperator luteocupreus': ['oak', 'calc'],
  'Neoboletus luridiformis': ['spruce beech oak pine', 'acid'],
  'Neoboletus junquilleus': ['beech oak', 'any'],
  'Neoboletus venenatus': ['fir spruce', 'any'],
  'Suillellus luridus': ['oak beech lime hornbeam', 'calc', 'park'],
  'Suillellus queletii': ['oak lime beech', 'calc'],
  'Suillellus mendax': ['beech oak fir', 'any'],
  'Suillellus comptus': ['oak', 'calc'],
  'Cyanoboletus pulverulentus': ['oak beech', 'acid'],
  'Hemileccinum impolitum': ['oak', 'calc'],
  'Hemileccinum depilatum': ['hornbeam hazel', 'calc'],
  'Imleria badia': ['spruce pine beech', 'acid'],
  'Xerocomus subtomentosus': ['oak beech spruce', 'any'],
  'Xerocomus ferrugineus': ['spruce pine fir', 'acid'],
  'Xerocomus chrysonemus': ['oak', 'any'],
  'Xerocomus silwoodensis': ['aspen', 'calc'],
  'Xerocomellus chrysenteron': ['beech oak spruce', 'any'],
  'Xerocomellus pruinatus': ['beech oak spruce', 'acid'],
  'Xerocomellus porosporus': ['oak beech lime', 'any'],
  'Xerocomellus cisalpinus': ['oak lime beech', 'any', 'park'],
  'Xerocomellus ripariellus': ['willow aspen', 'any', 'wet'],
  'Xerocomellus redeuilhii': ['oak', 'any'],
  'Xerocomellus marekii': ['oak beech', 'any'],
  'Hortiboletus rubellus': ['oak', 'any', 'park'],
  'Hortiboletus engelii': ['oak', 'calc', 'park'],
  'Rheubarbariboletus armeniacus': ['oak chestnut', 'acid'],
  'Aureoboletus gentilis': ['oak beech chestnut', 'any'],
  'Aureoboletus moravicus': ['oak', 'any'],
  'Aureoboletus projectellus': ['pine', 'acid', 'sand'],
  'Chalciporus piperatus': ['birch pine spruce', 'acid'],
  'Chalciporus amarellus': ['spruce pine', 'acid'],
  'Chalciporus rubinus': ['oak', 'any', 'park'],
  'Pseudoboletus parasiticus': ['', 'acid', 'parasite'],
  'Tylopilus felleus': ['spruce pine beech', 'acid'],
  'Porphyrellus porphyrosporus': ['spruce beech fir', 'acid'],
  'Strobilomyces strobilaceus': ['beech spruce fir', 'any'],
  'Leccinum scabrum': ['birch', 'any'],
  'Leccinum versipelle': ['birch', 'acid'],
  'Leccinum aurantiacum': ['aspen', 'any'],
  'Leccinum vulpinum': ['pine', 'acid'],
  'Leccinum duriusculum': ['aspen', 'calc'],
  'Leccinum variicolor': ['birch', 'acid', 'bog'],
  'Leccinum holopus': ['birch', 'acid', 'bog'],
  'Leccinum piceinum': ['spruce', 'acid'],
  'Leccinum quercinum': ['oak', 'any'],
  'Leccinum albostipitatum': ['aspen', 'any'],
  'Leccinum melaneum': ['birch', 'acid'],
  'Leccinum cyaneobasileucum': ['birch', 'any'],
  'Leccinum schistophilum': ['birch', 'acid'],
  'Leccinellum pseudoscabrum': ['hornbeam hazel', 'any'],
  'Leccinellum crocipodium': ['oak', 'any'],
  'Leccinellum lepidum': ['holmoak', 'any'],
  'Leccinellum corsicum': ['cistus', 'acid'],
  'Gyroporus castaneus': ['oak chestnut beech', 'acid', 'sand'],
  'Gyroporus cyanescens': ['birch spruce pine', 'acid', 'sand'],
  'Gyroporus ammophilus': ['pine', 'any', 'sand'],
  'Gyrodon lividus': ['alder', 'any', 'wet'],
  'Suillus luteus': ['pine', 'any', 'sand'],
  'Suillus grevillei': ['larch', 'any'],
  'Suillus granulatus': ['pine', 'calc'],
  'Suillus bovinus': ['pine', 'acid', 'sand'],
  'Suillus variegatus': ['pine', 'acid', 'sand'],
  'Suillus viscidus': ['larch', 'any'],
  'Suillus collinitus': ['pine', 'calc'],
  'Suillus placidus': ['stonepine', 'acid'],
  'Suillus plorans': ['stonepine', 'any'],
  'Suillus sibiricus': ['stonepine', 'any'],
  'Suillus cavipes': ['larch', 'acid'],
  'Suillus tridentinus': ['larch', 'calc'],
  'Suillus flavidus': ['pine', 'acid', 'bog'],
  'Suillus lakei': ['douglas', 'any'],
  'Suillus bellinii': ['pine', 'any', 'sand'],
  'Suillus mediterraneensis': ['pine', 'calc'],
  'Lanmaoa fragrans': ['oak chestnut', 'any'],
  'Buchwaldoboletus lignicola': ['pine', 'any', 'wood'],
  'Buchwaldoboletus hemichrysus': ['pine', 'any', 'wood'],
  'Phylloporus pelletieri': ['beech oak spruce', 'acid'],
};

const path = new URL('./species.json', import.meta.url);
const list = JSON.parse(await readFile(path, 'utf8'));
const missing = list.filter(s => !H[s.sci]).map(s => s.sci);
if (missing.length) throw new Error('no habitat for: ' + missing.join(', '));
for (const s of list) {
  const [trees, soil, extra = ''] = H[s.sci];
  s.trees = trees.split(' ').filter(Boolean);
  s.soil = soil;
  s.extra = extra.split(' ').filter(Boolean);
}
await writeFile(path, '[\n  ' + list.map(s => JSON.stringify(s)).join(',\n  ') + '\n]\n');
console.log('habitat for', list.length);
